version: "3.8"

services:
  mutltiapp-backend:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: mutltiapp-backend
    volumes:
      - ./MultyTestApp:/app
    working_dir: /app
    environment:
      - ASPNETCORE_URLS=http://*:5010
    ports:
      - "5010:5010"
    networks:
      - multiapp-network
    command: bash -c "dotnet publish -c Release ./MultyTestApp.csproj -o ./publish && dotnet ./publish/MultyTestApp.dll"
  
  mutltiapp-frontend:
    image: mcr.microsoft.com/dotnet/sdk:6.0
    container_name: mutltiapp-frontend
    volumes:
      - ./BlazorApp1:/app
    working_dir: /app
    environment:
      - ASPNETCORE_URLS=http://*:5011
    ports:
      - "5011:5011"
    networks:
      - multiapp-network
    command: bash -c "dotnet publish -c Release ./BlazorApp1.csproj -o ./publish && dotnet ./publish/BlazorApp1.dll"

networks:
  multiapp-network:
    driver: bridge